spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2/PRODUCT
    username: dtuser
    password:

server:
    port: 9010


feign:
  hystrix:
    enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/products/v2/api-docs

application:
  name:
    text: coe-dev

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream,refresh'
