products:
  prefix: 'E2E'

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/dt
    driver-class-name: org.mariadb.jdbc.Driver
    username: dtuser
    password: service

feign:
  hystrix:
    enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/products/v2/api-docs
        
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream,refresh'
